import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import MarkdownIt from 'markdown-it';
import texmath from 'markdown-it-texmath';
import katex from 'katex';

const root = process.cwd();
const out = path.join(root, '_site');
const md = new MarkdownIt({html: true, typographer: true}).use(texmath, {engine: katex, delimiters: 'dollars', katexOptions: {throwOnError: false}});
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const origin = 'https://maopaoa.github.io';
const walk = dir => fs.existsSync(dir) ? fs.readdirSync(dir, {withFileTypes:true}).flatMap(e => e.isDirectory() ? walk(path.join(dir,e.name)) : [path.join(dir,e.name)]) : [];
const posts = walk('_posts').filter(p => p.endsWith('.md')).map(file => {
  const {data,content} = matter(fs.readFileSync(file,'utf8'));
  const kind = data.kind || (file.includes('/poem/') ? 'poetry' : file.includes('/novel/') ? 'fiction' : 'research');
  const body = content.replace(/^\s*#\s+[^\n]+\n/, '');
  const date = data.date instanceof Date ? data.date : new Date(String(data.date).replace(/^(\d{4})-(\d{1,2})-(\d{1,2}).*$/, (_,y,m,d) => `${y}-${m.padStart(2,'0')}-${d.padStart(2,'0')}T00:00:00Z`));
  if (!data.title || Number.isNaN(date.getTime())) throw new Error(`Missing title or invalid date: ${file}`);
  const category = file.includes('/literature/') ? 'literature' : file.split('/')[1];
  const slug = path.basename(file,'.md').replace(/^\d{4}-\d{1,2}-\d{1,2}-/, '').replace(/ /g,'-');
  const url = data.permalink || `/posts/${category}/${slug}`;
  const excerpt = data.description || body.split('\n').filter(l => l.trim() && !/^\s*#/.test(l))[0]?.trim() || '';
  return {...data, file, date, kind, body, excerpt, url, html: md.render(body), minutes: Math.max(1,Math.ceil(body.replace(/\s/g,'').length/400))};
}).sort((a,b) => b.date-a.date || a.title.localeCompare(b.title,'zh'));
const labels = {fiction:'小说 / FICTION',poetry:'诗歌 / POETRY',research:'研究 / RESEARCH'};
const date = p => p.date.toISOString().slice(0,10).replaceAll('-','.');
const link = p => esc(p.url);
const arrow = '<span aria-hidden="true">↗</span>';
const art = `<div class="landscape" aria-hidden="true"><svg viewBox="0 0 800 560" fill="none"><defs><radialGradient id="wash"><stop stop-color="#bbae96" stop-opacity=".25"/><stop offset="1" stop-color="#bbae96" stop-opacity="0"/></radialGradient></defs><ellipse cx="430" cy="285" rx="330" ry="260" fill="url(#wash)"/><g class="contours">${Array.from({length:64},(_,i)=>{const y=90+i*6;return `<path d="M ${35+i*.7} ${y+120} C 150 ${y+140}, 150 ${y-95}, 315 ${y-45} S 435 ${y+170}, 575 ${y+70} S 700 ${y-55}, 810 ${y+15}"/>`}).join('')}</g><circle cx="579" cy="140" r="43" class="sun"/><path class="axis" d="M 35 465 H 765 M 579 80 V 495"/><text x="36" y="492">FIG. 01 — A LANDSCAPE OF THOUGHT</text><text x="687" y="492">∞ / 01</text></svg><span class="art-caption">在现实与想象之间</span></div>`;
const nav = active => `<header class="site-header"><a class="brand" href="/" aria-label="Maopao home">maopao<span class="brand-dot">.</span></a><nav aria-label="主导航"><a ${active==='fiction'?'aria-current="page"':''} href="/literature">小说<span>Fiction</span></a><a ${active==='poetry'?'aria-current="page"':''} href="/poetry">诗歌<span>Poetry</span></a><a ${active==='research'?'aria-current="page"':''} href="/research">研究<span>Research</span></a><a ${active==='about'?'aria-current="page"':''} href="/about">关于<span>About</span></a></nav><button class="theme-toggle" aria-label="切换夜间阅读" title="切换夜间阅读"><span aria-hidden="true">◐</span></button></header>`;
const footer = `<footer class="site-footer"><div><a class="brand" href="/">maopao<span class="brand-dot">.</span></a><p>写作，是另一种观察。</p></div><div class="footer-links"><a href="/archive">全部文章 ${arrow}</a><a href="/atom.xml">RSS ${arrow}</a><a href="https://github.com/MaopaoA">GitHub ${arrow}</a><a href="https://www.zhihu.com/people/maopao666/activities">知乎 ${arrow}</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Maopao</span><span>FICTION · POETRY · INTELLIGENCE</span><a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">文字 / CC BY-SA 4.0</a></div></footer>`;
function shell(title,content,{active='',url='/',description='Maopao 的个人写作与研究空间。小说、诗歌，以及关于人工智能的理论研究与观察。',article=false}={}) {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} · Maopao</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f3f0e8"><link rel="canonical" href="${origin}${esc(url)}"><meta property="og:title" content="${esc(title)} · Maopao"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:url" content="${origin}${esc(url)}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/atom+xml" title="Maopao" href="/atom.xml"><script src="/assets/theme.js"></script><link rel="stylesheet" href="/assets/site.css">${article?'<link rel="stylesheet" href="/assets/katex/katex.min.css">':''}<script src="/assets/site.js" defer></script></head><body><a class="skip-link" href="#main">跳至正文</a>${article?'<div class="reading-progress" aria-hidden="true"></div>':''}<div class="site-wrap">${nav(active)}<main id="main">${content}</main>${footer}</div></body></html>`;
}
function write(url,html) {const target = url.endsWith('.html') ? path.join(out,url) : path.join(out,url,'index.html');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,html);}
function row(p,i) {return `<a class="entry-row" href="${link(p)}" data-kind="${p.kind}" data-search="${esc(p.title+' '+p.excerpt)}"><span class="entry-number">${String(i+1).padStart(2,'0')}</span><div class="entry-text"><h3>${esc(p.title)}</h3><p>${esc(p.excerpt.slice(0,95))}${p.excerpt.length>95?'…':''}</p></div><div class="entry-meta"><span>${labels[p.kind]}</span><time datetime="${p.date.toISOString()}">${date(p)}</time></div><span class="entry-arrow" aria-hidden="true">↗</span></a>`;}
fs.mkdirSync(out,{recursive:true});
fs.cpSync('assets',path.join(out,'assets'),{recursive:true});
fs.cpSync('node_modules/katex/dist',path.join(out,'assets/katex'),{recursive:true});
fs.cpSync('image',path.join(out,'image'),{recursive:true});
fs.writeFileSync(path.join(out,'.nojekyll'),'');
const fiction = posts.filter(p=>p.kind==='fiction');
const poetry = posts.filter(p=>p.kind==='poetry');
const research = posts.filter(p=>p.kind==='research');
const featured = fiction.find(p=>p.title==='望向黑色的眼睛') || fiction[0];
const poem = poetry[0];
const home = `<section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="live-dot"></span> MAOPAO’S PERSONAL JOURNAL</p><h1>世界的另一种<br><em>读法<span class="hero-period">。</span></em></h1><p class="hero-description">在故事里寻找真实，<br>在智能的边界，重新理解我们自己。</p><a class="text-link" href="#latest">翻开这本手记 <span aria-hidden="true">↓</span></a></div>${art}<div class="hero-foot"><span>小说 · 诗歌 · 人工智能</span><span>AN OPEN-ENDED EXPLORATION</span><span>南京，中国 / NANJING, CN</span></div></section>
<section class="selected"><div class="section-heading"><h2><span>01 /</span> 从这里读起 <small>SELECTED WRITING</small></h2><a href="/literature">走进故事 ${arrow}</a></div><div class="selected-grid">${featured?`<a class="feature-story" href="${link(featured)}"><div class="feature-top"><span class="eyebrow">小说 / FICTION</span><span>精选 · ${featured.date.getUTCFullYear()}</span></div><div class="story-graphic" aria-hidden="true"><span class="eye eye-one"></span><span class="eye eye-two"></span><span class="graphic-caption">THE QUIET OF LOOKING</span></div><div class="feature-bottom"><h3>${esc(featured.title)}</h3><p>${esc(featured.excerpt.slice(0,105))}…</p><span class="text-link">阅读作品 <span>↗</span></span></div></a>`:''}${poem?`<a class="feature-poem" href="${link(poem)}"><div class="feature-top"><span class="eyebrow">诗歌 / POETRY</span><span>001</span></div><h3>${esc(poem.title)}</h3><div class="poem-fragment">${md.render(poem.body.split('\n').slice(0,10).join('\n'))}</div><div class="poem-bottom"><span>一些微小而遥远的事物。</span><span aria-hidden="true">↗</span></div><span class="poem-watermark" aria-hidden="true">诗</span></a>`:''}</div></section>
<section class="latest" id="latest"><div class="section-heading"><h2><span>02 /</span> 最近的文字 <small>RECENT ENTRIES</small></h2><a href="/archive">全部文章 ${arrow}</a></div>${posts.slice(0,4).map(row).join('')}</section>
<section class="research-note"><div class="research-symbol" aria-hidden="true"><span>∴</span><i></i></div><div><p class="eyebrow">另一条探索的路径 / RESEARCH NOTES</p><h2>当机器开始思考，<br>我们如何理解「理解」？</h2><p>关于人工智能的理论、观察与尚未解答的问题。</p><a class="text-link" href="/research">进入研究手记 ${arrow}</a></div><span class="research-margin" aria-hidden="true">HUMAN / MACHINE</span></section>`;
write('/',shell('写作与研究',home));
const collection = (kind,title,en,description,list,url) => `<section class="collection-head"><p class="eyebrow">${en} / ${String(list.length).padStart(2,'0')} ENTRIES</p><h1>${title}<span>。</span></h1><p>${description}</p></section>${list.length?`<div class="collection-list">${list.map(row).join('')}</div>`:`<div class="empty-state"><span aria-hidden="true">∴</span><h2>问题先于答案。</h2><p>这里将收录关于人工智能的理论研究与观察。<br>第一篇手记尚未发表。</p><a class="text-link" href="/literature">先读一篇故事 ${arrow}</a></div>`}`;
write('/literature',shell('小说',collection('fiction','故事的另一面','FICTION','记忆、日常，以及那些未被说出的部分。',fiction,'/literature'),{active:'fiction',url:'/literature'}));
write('/poetry',shell('诗歌',collection('poetry','微小的回声','POETRY','留下一瞬间，也留下它的沉默。',poetry,'/poetry'),{active:'poetry',url:'/poetry'}));
write('/research',shell('研究',collection('research','智能与观察','AI · THEORY · OBSERVATIONS','在人工智能的边界，记录思考的过程。',research,'/research'),{active:'research',url:'/research'}));
write('/archive',shell('全部文章',`<section class="collection-head"><p class="eyebrow">THE INDEX / ${posts.length} ENTRIES</p><h1>文字的索引<span>。</span></h1><p>写下的事物，在这里相遇。</p></section><div class="archive-tools"><div class="filters" role="group" aria-label="按类型筛选"><button class="active" aria-pressed="true" data-filter="all">全部 <span>${posts.length}</span></button>${[['fiction','小说',fiction],['poetry','诗歌',poetry],['research','研究',research]].map(([k,n,l])=>`<button aria-pressed="false" data-filter="${k}">${n} <span>${l.length}</span></button>`).join('')}</div><label class="search-label"><span class="sr-only">搜索文章标题与摘要</span><input type="search" placeholder="寻找一段文字…" aria-label="搜索文章标题与摘要"><span aria-hidden="true">⌕</span></label></div><p class="sr-only" id="result-count" aria-live="polite">${posts.length} 篇文章</p><div class="collection-list">${posts.map(row).join('')}</div><p class="search-empty" hidden>这里暂时没有对应的文字。试试另一个关键词。</p>`,{url:'/archive'}));
write('/about',shell('关于',`<section class="about-layout"><div><p class="eyebrow">ABOUT / 关于</p><h1>观察世界，<br><em>也观察自己。</em></h1><p class="about-signature">Maopao<span> / 冒泡</span></p></div><div class="about-copy"><p class="about-intro">这是一个用来写作与思考的个人空间。</p><p>故事里有记忆中的小镇、漫长的成长，以及日常生活不经意间露出的缝隙。诗歌记录更微小的事物：夜晚、海水、一只楼下的猫。</p><p>另一条线索是人工智能。我将在这里发表理论研究与观察，记录那些关于智能、理解与人的问题。</p><p>小说、诗歌与研究，是不同的观察方式。它们在这里并行。</p><div class="about-details"><div><span>坐标 / BASED IN</span><p>南京，中国</p></div><div><span>教育 / EDUCATION</span><p>南京大学</p></div></div><a class="text-link" href="https://github.com/MaopaoA">在 GitHub 找到我 ${arrow}</a></div></section>`,{active:'about',url:'/about'}));
for (const p of posts) {
 const siblings = posts.filter(q=>q.kind===p.kind);const i=siblings.indexOf(p);const next=siblings[i+1]||siblings[i-1];
 write(p.url,shell(p.title,`<article class="reading-page ${p.kind==='poetry'?'poem-reading':''}"><header class="reading-head"><a class="eyebrow" href="/${p.kind==='fiction'?'literature':p.kind==='poetry'?'poetry':'research'}">← ${labels[p.kind]}</a><h1>${esc(p.title)}</h1><div class="reading-meta"><time datetime="${p.date.toISOString()}">${date(p)}</time><span>MAOPAO</span><span>约 ${p.minutes} 分钟</span></div><div class="reading-controls"><span>阅读字号</span><button data-font="smaller" aria-label="缩小阅读字号">A−</button><button data-font="larger" aria-label="放大阅读字号">A+</button></div></header><div class="prose">${p.html}</div><div class="reading-end"><span>· · ·</span><p>Maopao / ${p.date.getUTCFullYear()}</p></div><nav class="article-nav" aria-label="更多作品"><a href="/archive">← 返回文字索引</a>${next?`<a href="${link(next)}"><small>继续阅读</small>${esc(next.title)} →</a>`:''}</nav></article>`,{active:p.kind,url:p.url,description:p.excerpt.slice(0,150),article:true}));
}
write('/404.html',shell('此页留白',`<section class="not-found"><p class="eyebrow">404 / A PAGE NOT FOUND</p><h1>此页留白<span>。</span></h1><p>你寻找的文字不在这里。也许在下一页。</p><a class="text-link" href="/">回到首页 ${arrow}</a></section>`,{url:'/404.html'}));
for (const [old,to] of [['/math','/research'],['/career','/research'],['/resume','/about'],['/tags','/archive'],['/comments','/about']]) write(old,shell('页面已迁移',`<section class="not-found"><h1>换一个角度。</h1><a class="text-link" href="${to}">前往新页面 ${arrow}</a></section><script>location.replace(${JSON.stringify(to)})</script>`,{url:to}));
const updated=posts[0]?.date.toISOString()||new Date().toISOString();
fs.writeFileSync(path.join(out,'atom.xml'),`<?xml version="1.0" encoding="utf-8"?><feed xmlns="http://www.w3.org/2005/Atom"><title>Maopao · 写作与研究</title><link href="${origin}/atom.xml" rel="self"/><link href="${origin}/"/><id>${origin}/</id><updated>${updated}</updated><author><name>Maopao</name></author>${posts.map(p=>`<entry><title>${esc(p.title)}</title><link href="${origin}${link(p)}"/><id>${origin}${link(p)}</id><updated>${p.date.toISOString()}</updated><content type="html">${esc(p.html)}</content></entry>`).join('')}</feed>`);
const urls=['/','/literature','/poetry','/research','/about','/archive',...posts.map(p=>p.url)];
fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${origin}${esc(u)}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(posts.map(({title,url,kind})=>({title,url,kind})),null,2));
console.log(`Built ${posts.length} original works and ${urls.length} pages into _site.`);
