// Reproduce the original site's presentation without its Jekyll/Lanyon runtime.
export function createPresentation({config, legacy, posts, featured, profileHTML, md, esc, labels, date, row}) {
  const avatar = config.avatar || '/image/avatar.png';
  const siteTitle = config.title || legacy.title || "maopao's blog";
  const icon = name => name === 'rss' ? '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="5" cy="19" r="2" fill="currentColor"/><path d="M3 11a10 10 0 0 1 10 10M3 4a17 17 0 0 1 17 17" fill="none" stroke="currentColor" stroke-width="2"/></svg>' : name === 'github' ? '<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 2a10 10 0 0 0-3.16 19.49c.5.09.68-.22.68-.48v-1.86c-2.78.6-3.37-1.18-3.37-1.18-.45-1.16-1.11-1.47-1.11-1.47-.91-.62.07-.61.07-.61 1 .07 1.53 1.03 1.53 1.03.89 1.53 2.34 1.09 2.91.83.09-.65.35-1.09.64-1.34-2.22-.25-4.55-1.11-4.55-4.94 0-1.09.39-1.99 1.03-2.69-.1-.26-.45-1.28.1-2.66 0 0 .84-.27 2.75 1.03A9.6 9.6 0 0 1 12 6.82c.85 0 1.7.11 2.5.33 1.91-1.3 2.75-1.03 2.75-1.03.55 1.38.2 2.4.1 2.66.64.7 1.03 1.6 1.03 2.69 0 3.84-2.34 4.68-4.57 4.93.36.31.68.92.68 1.85v2.75c0 .27.18.58.69.48A10 10 0 0 0 12 2z"/></svg>' : '<span aria-hidden="true" class="zhihu-icon">知</span>';
  const social = `<a href="/subscribe" title="RSS" aria-label="RSS 订阅">${icon('rss')}</a>${config.social.map(s=>`<a href="${esc(s.url)}" title="${esc(s.label)}" aria-label="${esc(s.label)}">${icon(s.label==='GitHub'?'github':'zhihu')}</a>`).join('')}`;
  const music = config.music ? `<div class="home-profile-music"><iframe title="Spotify 音乐" src="${esc(config.music)}" width="100%" height="80" loading="lazy" allow="autoplay; encrypted-media; clipboard-write; fullscreen; picture-in-picture"></iframe></div>` : '';
  const profile = `<aside class="home-profile"><div class="home-profile-avatar"><a href="/about" aria-label="关于 Maopao"><img src="${esc(avatar)}" width="120" height="120" alt="Maopao 的头像"></a></div><div class="home-profile-text"><div class="profile-text" lang="en">${profileHTML}</div>${music}</div><div class="home-profile-social">${social}</div></aside>`;
  const navigation = [
    ['/', 'Home'], ['/literature', 'Literary Creation'],
    ['/research', 'Math &amp; AI'], ['/poetry', 'Poetry'],
    ['/archive', 'Archive'], ['/about', 'About'], ['/subscribe', 'RSS'],
  ];
  const nav = active => `<header class="masthead"><a class="masthead-link" href="/" aria-label="Maopao 首页"><h1 class="masthead-title">${esc(siteTitle)}</h1></a><button class="theme-toggle" aria-label="切换夜间阅读" title="切换夜间阅读"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 14.1A9 9 0 0 1 9.9 3.2 9 9 0 1 0 20.8 14.1Z"/></svg></button></header><button class="menu-toggle" type="button" aria-label="打开菜单" aria-expanded="false" aria-controls="site-menu"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18"/></svg></button><div class="menu-backdrop" hidden></div><aside class="site-menu" id="site-menu" role="dialog" aria-modal="true" aria-label="导航与搜索" hidden><button class="menu-close" type="button" aria-label="关闭菜单">×</button><a class="menu-avatar" href="/about"><img src="${esc(avatar)}" width="120" height="120" alt="Maopao 的头像"></a><nav aria-label="主导航">${navigation.map(([url,title])=>`<a href="${url}" ${({'fiction':'/literature', 'poetry':'/poetry', 'research':'/research','archive':'/archive','about':'/about'}[active]===url)?'aria-current="page"':''}>${title}</a>`).join('')}</nav><form class="home-search" action="/archive" method="get"><label for="home-query">搜索文章</label><div><input id="home-query" name="q" type="search" placeholder="标题、正文或标签"><button type="submit" aria-label="搜索">→</button></div></form><div class="menu-social">${social}</div><a class="menu-logo" href="/"><img src="/image/icon.png" width="48" height="48" alt="Maopao 博客图标"></a></aside>`;
  const footer = `<footer class="site-footer"><p class="site-footer-brand">© ${new Date().getFullYear()} ${esc(siteTitle)}</p><div class="site-footer-links"><a href="/archive">Archive</a><a href="/subscribe">RSS</a><a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a></div></footer>`;
  const homeCard = (p, isFeatured=false) => `<article class="home-card${isFeatured?` selected-card ${p.kind}`:''}"><a href="${esc(p.url)}" class="home-card-title">${esc(p.title)}</a><div class="home-meta"><time datetime="${p.date.toISOString()}">${p.date.toLocaleDateString('en-US',{timeZone:'UTC',year:'numeric',month:'short',day:'numeric'})}</time><span class="home-category">${labels[p.kind]}</span></div>${p.kind==='poetry'?`<div class="home-excerpt poem-excerpt">${md.render(p.body.split('\n').slice(0,10).join('\n'))}</div>`:`<p class="home-excerpt">${esc(p.excerpt.slice(0,140))}${p.excerpt.length>140?'…':''}</p>`}</article>`;
  const archive = featured.length ? featured : posts.slice(3,6);
  const home = `<nav class="home-sections-nav" aria-label="文章分类"><a href="/literature">Literary Creation</a><a href="/research">Math &amp; AI</a></nav><div class="home-three-col"><section class="home-col home-col-left"><h2 class="home-section-title">Archive</h2>${archive.map(p=>homeCard(p,featured.includes(p))).join('')}<a class="home-more" href="/archive">全部文章 →</a></section><section class="home-col home-col-center"><h2 class="home-section-title">Latest</h2>${posts.slice(0,3).map(p=>homeCard(p)).join('')}</section><section class="home-col home-col-right"><h2 class="home-section-title">Literary &amp; Profile</h2>${profile}</section></div>`;
  const literature = `<section class="section-page"><header class="collection-head"><h1>Literary Creation</h1></header><div class="literature-layout"><div class="literature-main"><h2 class="literature-subtitle">Novels &amp; Essays</h2><div class="collection-list">${posts.filter(p=>p.kind==='fiction').map(row).join('')}</div></div><aside class="literature-sidebar"><h2 class="literature-subtitle">Poetry</h2>${posts.filter(p=>p.kind==='poetry').map(p=>`<article class="poem-card"><a class="poem-title" href="${esc(p.url)}">${esc(p.title)}</a><time class="poem-date" datetime="${p.date.toISOString()}">${date(p)}</time><div class="poem-preview">${md.render(p.body.split('\n').slice(0,10).join('\n'))}</div></article>`).join('')}<a class="home-more" href="/poetry">全部诗歌 →</a></aside></div></section>`;
  const about = `<section class="about-layout"><header class="collection-head"><h1>About</h1></header><div class="about-copy"><a class="about-avatar" href="/"><img src="${esc(avatar)}" width="120" height="120" alt="Maopao 的头像"></a><div lang="en" class="original-profile">${profileHTML}</div><div class="about-details"><div><span>所在地</span><p>南京，中国</p></div><div><span>教育</span><p>南京大学</p></div></div><div class="home-profile-social">${social}</div>${music}</div></section>`;
  return {nav, footer, home, literature, about, siteTitle};
}
